add_languages("c++17")
add_requires("fmt 10.1.1")
target("stlog")
    set_kind("static")
    add_includedirs("include", {public = true})
    add_files("src/*.cpp")
    add_headerfiles("include/(stlog/*.h)")
    add_packages("fmt")
target_end()
